### ISSUE TITLE
General FYI (use of `sub ... is rw` etc)

### ISSUE THREAD

**Issue by raiph** [tinmarino/nogil#1]
Dunno if you're still interested in Raku but fwiw I am looking forward to Raku and/or a Raku like language having nice support for no sigils.

I agree with some decisions you've made (eg `no strict;` and `foo` can be written with or without its sigil.) I have an additional idea but I think doing something about it needs to wait until RakuAST lands.

In the meantime, note that:
```
sub term:<fct> is rw { $ }
fct = 2;
say fct; # 2
```

**Comment by tinmarino** [comment]
Thank you @raiph, I did not know this declaration syntax.
Sorry for the delay, I stopped coding in Raku for a while as it is hard to release.
